"""Update the manuscript DNS subsection to the uniform-injection result."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = Path(r"D:\OneDrive - HHU\My paper\11Laplace-Taylor discovery")
PAPER = PAPER_DIR / "main.tex"
PAPER_FIGURES = PAPER_DIR / "figures"


START = r"\subsection{Upscaling of 2D microscopic solute transport simulation}"
END = r"\section{Discussion}"


NEW_BLOCK = r"""\subsection{Upscaling of 2D microscopic solute transport simulation}
\label{sec:dns_gamm_plum}
The second example differs from the manufactured fractional-equation benchmarks above. Here the data are not generated by solving a known fractional equation. Instead, they are produced by a direct numerical simulation of groundwater flow and particle transport in a 2D heterogeneous conductivity field. A correlated two-dimensional hydraulic-conductivity field \(K(x,y)\) is generated with GSTools using an exponential covariance model, correlation length \(1.0\), and a Gamma marginal distribution with shape parameter \(0.75\), scale \(0.35\), lower cutoff \(K_{\min}=10^{-6}\), and random seed \(2026\). The computational domain is \(100\times 200\), discretized on a \(1000\times 2000\) MODFLOW grid with \(\Delta x=\Delta y=0.1\).

MODFLOW 6 is then used to solve the steady saturated flow problem with fixed heads \(h=100\) on the left boundary and \(h=0\) on the right boundary. The porosity is \(0.35\), and the specific discharge is saved and converted to pore velocity. Particle transport is simulated by MODPATH 7 with pure forward advective tracking. In contrast to the flux-weighted diagnostic run, the final DNS case uses a uniform inlet release: \(4000\) particles are placed uniformly along the upstream boundary so that slow inlet streamlines are not suppressed by the release rule. MODPATH outputs particle positions at \(80\) observation times on \(t\in[0,100]\). The one-dimensional concentration field \(c(x,t)\) used for discovery is obtained by binning particle \(x\)-positions, retaining the plume window \(x\in[0,62.75]\), using \(240\) spatial bins, and applying a one-bin Gaussian smoothing filter.

The Eulerian field statistics confirm the intended heavy-tailed transport setting. The generated \(K\) field has fitted Gamma shape \(0.750\), matching the prescribed marginal distribution. Positive \(v_x\) values have a fitted Gamma shape about \(1.21\), while the waiting-time proxy \(1/v_x\) has an empirical log--CCDF tail slope about \(0.91\). This supports the expectation that uniform injection should expose slow pathways more strongly than flux-weighted injection.

For the prediction diagnostic, the sparse-regression rows are restricted to the first \(80\%\) of the observation interval, while the later snapshots are used only for equation-level prediction. Because the earliest particle cloud has not yet traversed enough heterogeneous structure to represent an effective medium, and because the fractional law is interpreted as a late-time asymptotic closure, the sparse regression window excludes the first two snapshots. The discovery configuration also crops the spatial domain to mitigate boundary-condition effects, using \(x\in[4,26]\), \(t_{\min}=2.532\), and \(t_{\max}=80\). On the discrete DNS grid this corresponds to the actual fit range \(t\in[3.797,79.747]\). The snapshots from \(t=81.013\) to \(t=100\) are then reserved for prediction assessment. The neural network remains an internal differentiable reconstruction device for operator evaluation.

\begin{figure}[htbp]
    \centering
    \begin{minipage}{0.32\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/dns_gamma075_uniform_logK_field_2d.png}\\[-0.2ex]
        \small (a) \(\log K(x,y)\)
    \end{minipage}
    \hfill
    \begin{minipage}{0.32\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/dns_gamma075_uniform_velocity_field_2d.png}\\[-0.2ex]
        \small (b) Pore-velocity overview
    \end{minipage}
    \hfill
    \begin{minipage}{0.32\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/dns_gamma075_uniform_concentration_xt_heatmap.png}\\[-0.2ex]
        \small (c) Exported \(c(x,t)\)
    \end{minipage}
    \caption{Mechanistic plume-simulation data used in the Gamma-field example with uniform inlet injection. The heterogeneous conductivity field is generated by GSTools, the steady flow field by MODFLOW 6, and the particle plume by MODPATH 7.}
    \label{fig:dns_g075_fiel}
\end{figure}

The same Gauss--Jacobi (G--J) route is applied to the trained tanh surrogate, using \(4000\) training points and \(2000\) validation points. The full physical RHS library is used in the sparse regression; correction terms are only internal order-update aids and are inactive in the reported equation. The selected sparse model is
\begin{equation}
    D_t^{0.8335}c = -0.6202\,\frac{\partial c}{\partial x} .
    \label{eq:dns_gamm_disc}
\end{equation}
This pure-advection structure is physically consistent with the simulator mechanism: MODPATH 7 performs advective particle tracking. This example is interpreted as an effective transport law extracted from microscopic simulation data. The fractional time order is an effective exponent relating the late-time plume evolution in a heterogeneous conductivity field \citep{hakoun2019upscaling}. The recovered order \(0.8335\) is close to, but not identical with, the Gamma shape parameter \(0.75\). The two quantities should not be identified as an analytical equality, because \(0.75\) is a medium parameter rather than a known PDE order; the remaining difference is plausibly caused by particle noise, NN reconstruction error, and imperfect numerical differentiation of the reconstructed plume.

We further use Eq.~\eqref{eq:dns_gamm_disc} to forecast the concentration field beyond the \(t=80\) split, including the held-out \(t=100\) profile. For the equation \(D_t^\alpha c=\theta c_x\), \(\theta<0\), and a Dirac initial plume \(c(x,0)=\delta(x-x_0)\), the Fourier--Laplace transform solution is
\begin{equation}
    \widehat{\widetilde c}(k,s)
    =
    \frac{s^{\alpha-1}\exp(-ikx_0)}
    {s^\alpha-\theta ik}.
    \label{eq:dns_gamm_fl}
\end{equation}
Thus the initial condition is imposed analytically through the transform of the Dirac source rather than by taking an FFT of the DNS initial snapshot. For \(\theta<0\), writing \(v=-\theta\), the inverse Fourier transform gives the one-sided Laplace-domain kernel
\begin{equation}
    \widetilde c(x,s)
    =
    \frac{s^{\alpha-1}}{v}
    \exp\!\left[-\frac{(x-x_0)s^\alpha}{v}\right],
    \qquad x\ge x_0 ,
    \label{eq:dns_gamm_laplace_kernel}
\end{equation}
and \(\widetilde c(x,s)=0\) for \(x<x_0\). The remaining inverse Laplace transform is evaluated numerically with the same accelerated inversion formula used for the fractional analytical solver.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.96\textwidth]{figures/dns_gamma075_lc1_uniform_kmin1e6_full_domain_t80split_heatmaps.png}
    \caption{Full-domain qualitative comparison between DNS and the discovered-equation prediction for the uniform-injection DNS plume. Both panels use the full exported space--time grid, and the dashed white line marks \(t=80\), separating the sparse-discovery fit window from the prediction window.}
    \label{fig:dns_g075_full_heat}
\end{figure}

\begin{figure}[htbp]
    \centering
    \begin{minipage}{0.48\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_linear.png}\\[-0.2ex]
        \small (a) Linear scale
    \end{minipage}
    \hfill
    \begin{minipage}{0.48\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figures/dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_loglog.png}\\[-0.2ex]
        \small (b) Log--log scale
    \end{minipage}
    \caption{Out-of-sample prediction at \(t=100\) for the uniform-injection DNS plume. DNS values are shown as symbols to reduce the visual impact of particle noise, and the discovered curve is the transform-domain solution of Eq.~\eqref{eq:dns_gamm_disc}.}
    \label{fig:dns_g075_forecast}
\end{figure}

The neural network is used here as an internal differentiable reconstruction device for derivative and fractional-operator evaluation, not as the final predictive model. The held-out comparison in Figure~\ref{fig:dns_g075_forecast} therefore displays only the DNS particle profile and the physics-constrained forecast from Eq.~\eqref{eq:dns_gamm_disc}. This compact Hx-only fractional law does not attempt to reproduce all particle-level fluctuations, but it extracts the dominant late-time pure-convection structure implied by the advective MODPATH mechanism. Across the \(t>80\) prediction snapshots, the full-domain prediction has mean mass-normalized relative \(L^2\) error \(0.272\). At \(t=100\), the one-dimensional profile comparison gives relative \(L^2\) error \(0.289\) and log-profile error \(0.167\). The result demonstrates model upscaling from microscopic heterogeneous-flow simulation to a compact fractional transport closure, while keeping the surrogate role internal to the discovery pipeline.

"""


def main() -> None:
    text = PAPER.read_text(encoding="utf-8")
    start = text.index(START)
    end = text.index(END, start)
    updated = text[:start] + NEW_BLOCK + text[end:]
    PAPER.write_text(updated, encoding="utf-8")

    copies = [
        (
            ROOT / "data" / "dns_gamma075_lc1_uniform_kmin1e6" / "logK_field_2d.png",
            PAPER_FIGURES / "dns_gamma075_uniform_logK_field_2d.png",
        ),
        (
            ROOT / "data" / "dns_gamma075_lc1_uniform_kmin1e6" / "velocity_field_2d.png",
            PAPER_FIGURES / "dns_gamma075_uniform_velocity_field_2d.png",
        ),
        (
            ROOT / "data" / "dns_gamma075_lc1_uniform_kmin1e6" / "concentration_xt_heatmap.png",
            PAPER_FIGURES / "dns_gamma075_uniform_concentration_xt_heatmap.png",
        ),
        (
            ROOT / "figures" / "dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_linear.png",
            PAPER_FIGURES / "dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_linear.png",
        ),
        (
            ROOT / "figures" / "dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_loglog.png",
            PAPER_FIGURES / "dns_gamma075_lc1_uniform_kmin1e6_forecast_t100_loglog.png",
        ),
        (
            ROOT / "figures" / "dns_gamma075_lc1_uniform_kmin1e6_full_domain_t80split_heatmaps.png",
            PAPER_FIGURES / "dns_gamma075_lc1_uniform_kmin1e6_full_domain_t80split_heatmaps.png",
        ),
    ]
    PAPER_FIGURES.mkdir(parents=True, exist_ok=True)
    for src, dst in copies:
        shutil.copy2(src, dst)
        print(f"copied {src} -> {dst}")
    print(f"updated {PAPER}")


if __name__ == "__main__":
    main()
